### ISSUE TITLE
user icon logo not available in create post section in community page

### ISSUE THREAD

**Issue by sravanpant** [sam1322/nextjs-reddit#1]
# This logo on the side of the create post section is not loading 
![image](https://github.com/sam1322/nextjs-reddit/assets/70965196/e973d963-04b4-42cd-97dd-39e0d2d6bd7c)
### The logo should appear like this
![image](https://github.com/sam1322/nextjs-reddit/assets/70965196/8e8520ec-3c88-47e2-a09e-e51bc1c28c2d)
### Pls rectify this

**Comment by sam1322** [comment]
it is now fixed
